### ISSUE TITLE
Add version command to gokart

### ISSUE THREAD

**Issue by AlexanderNelzin** [praetorian-inc/gokart#61]
Current `gokart` doesn't show its version now and it's not possible check in CI or on local machine that gokart is not outdated.

**Comment by isp1r0** [comment]
Hi @AlexanderNelzin - thanks so much for making this request and our apologies that it took us so long to fix it.

The recent merge of #64 takes care of this issue.  Please confirm the fix when you get a chance and check back often since we're now doubling down on our resources to improve GoKar and our other open source scanners.

**Comment by AlexanderNelzin** [comment]
Great! Thanks!
Waiting for release to use it.
